workspace/Image/src/beans/TableBean.java
package beans;

import dao.Database;
import java.sql.*;
import java.util.*;




public class TableBean {

    private String imageID;
    private String imageName;

    public String getImageName() {
        return imageName;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    public String getImageLength() {
        return imageLength;
    }

    public void setImageLength(String imageLength) {
        this.imageLength = imageLength;
    }
    private String imageLength;

    public String getImageID() {
        return imageID;
    }

    public void setImageID(String imageID) {
        this.imageID = imageID;
    }
    Connection MySQLcon = null;
    Statement stmt = null;
    PreparedStatement ps;
    ResultSet rs;

    public List<TableBean> getAllImage() {
        List<TableBean> imageInfo = new ArrayList<TableBean>();
        Connection con = Database.getConnection();
        try {
            stmt = con.createStatement();
            String strSql = "select image_id,Image_name from upload_image order by image_id ";
            //System.err.println("*select all***" + strSql);
            rs = stmt.executeQuery(strSql);
            while (rs.next()) {
                TableBean tbl = new TableBean();
                tbl.setImageID(rs.getString("image_id"));
                tbl.setImageName(rs.getString("Image_name"));
                imageInfo.add(tbl);
            }
        } catch (SQLException e) {
            System.out.println("Exception in getAllImage::" + e.getMessage());
        }
        return imageInfo;
    }
}

workspace/Image/src/WebContent/index.jsp
<% response.sendRedirect("index.jsf"); %>

workspace/Image/src/WebContent/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      >
    <h:head>
        <title>Image Upload</title>
    </h:head>
    <h:body>
        <h:form enctype="multipart/form-data">  
            <p:messages showDetail="true"/> 
            <p:panelGrid columns="2">
                <h:outputLabel for="image" value="Select Image: *" />
                <p:fileUpload value="#{uploadImage.file}" mode="simple" allowTypes="/(\.|\/)(gif|jpe?g|png)$/"/> 
                <f:facet name="footer">
                    <p:commandButton value="Submit" ajax="false" 
                                     actionListener="#{uploadImage.upload}"/></f:facet>
            </p:panelGrid>
            <p:spacer height="20"></p:spacer>
            <p:dataTable value="#{tableBean.allImage}" var="item" paginator="true" rows="5"
                         paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                         rowsPerPageTemplate="3,5,10" widgetVar="50" style="width: 60px;" >           
                <f:facet name="header">
                    <h:outputText value="Image showing from database" />
                </f:facet>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="Image Id" />
                    </f:facet>
                    <h:outputText value="#{item.imageID}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="Image Name" />
                    </f:facet>
                    <h:outputText value="#{item.imageName}"/>
                </p:column>
                <p:column>
                    <f:facet name="header">
                        <h:outputText value="Image" />
                    </f:facet>
                    <h:outputLink value="DisplayImage?Image_id=#{item.imageID}" target="_blank" >
                        <h:graphicImage value="DisplayImage?Image_id=#{item.imageID}" width="50" height="50"></h:graphicImage>
                    </h:outputLink>

                </p:column>
            </p:dataTable>
        </h:form> 
    </h:body>
</html>